Repository shivammathur/homebrew-php, pull requests merged in 2024-10, with the labels that each got.

#3181 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3179 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3185 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4

#3182 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3188 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3187 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3189 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3186 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4

#3193 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3191 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3190 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4

#3172 feat: install libphp with the ZTS package
  Formula/php-debug-zts.rb
Labels: build-complete, CI-no-fail-fast

#3196 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3197 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3194 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3199 php-debug-zts.rb: Build for icu4c@75
  Formula/php-debug-zts.rb
Labels: build-complete

#3200 php-debug.rb: Build for icu4c@75
  Formula/php-debug.rb
Labels: build-complete

#3201 php-zts.rb: Build for icu4c@75
  Formula/php-zts.rb
Labels: build-complete

#3225 php@7.4-zts: Build for icu4c@75
  Formula/php@7.4-zts.rb
Labels: build-complete

#3228 php@8.0-debug: Build for icu4c@75
  Formula/php@8.0-debug.rb
Labels: build-complete

#3223 php@7.4-debug-zts: Build for icu4c@75
  Formula/php@7.4-debug-zts.rb
Labels: build-complete

#3229 php@8.0-zts: Build for icu4c@75
  Formula/php@8.0-zts.rb
Labels: build-complete

#3237 php@8.2-zts: Build for icu4c@75
  Formula/php@8.2-zts.rb
Labels: build-complete

#3239 php@8.4-debug-zts: Build for icu4c@75
  Formula/php@8.4-debug-zts.rb
Labels: build-complete

#3236 php@8.2-debug: Build for icu4c@75
  Formula/php@8.2-debug.rb
Labels: build-complete

#3235 php@8.2-debug-zts: Build for icu4c@75
  Formula/php@8.2-debug-zts.rb
Labels: build-complete

#3238 php@8.2: Build for icu4c@75
  Formula/php@8.2.rb
Labels: build-complete

#3240 php@8.4-debug: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3202 php.rb: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3233 php@8.1-zts: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3232 php@8.1-debug: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3231 php@8.1-debug-zts: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3230 php@8.0: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3227 php@8.0-debug-zts: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3226 php@7.4: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3224 php@7.4-debug: Build for icu4c@75
  Formula/php@8.4-debug.rb
Labels: build-complete

#3246 php@8.5: Build for icu4c@75
  Formula/php@8.5.rb
Labels: build-complete

#3243 php@8.5-debug-zts: Build for icu4c@75
  Formula/php@8.5-debug-zts.rb
Labels: build-complete

#3242 php@8.4: Build for icu4c@75
  Formula/php@8.4.rb
Labels: build-complete

#3205 php@5.6-zts: Build for icu4c@75
  Formula/php@5.6-zts.rb
Labels: build-complete

#3245 php@8.5-zts: Build for icu4c@75
  Formula/php@5.6-zts.rb
Labels: build-complete

#3244 php@8.5-debug: Build for icu4c@75
  Formula/php@5.6-zts.rb
Labels: build-complete

#3210 php@7.0: Build for icu4c@75
  Formula/php@7.0.rb
Labels: build-complete

#3207 php@7.0-debug-zts: Build for icu4c@75
  Formula/php@7.0-debug-zts.rb
Labels: build-complete

#3208 php@7.0-debug: Build for icu4c@75
  Formula/php@7.0-debug.rb
Labels: build-complete

#3213 php@7.1-zts: Build for icu4c@75
  Formula/php@7.1-zts.rb
Labels: build-complete

#3204 php@5.6-debug: Build for icu4c@75
  Formula/php@5.6-debug.rb
Labels: build-complete

#3212 php@7.1-debug: Build for icu4c@75
  Formula/php@7.1-debug.rb
Labels: build-complete

#3215 php@7.2-debug-zts: Build for icu4c@75
  Formula/php@7.2-debug-zts.rb
Labels: build-complete

#3206 php@5.6: Build for icu4c@75
  Formula/php@5.6.rb
Labels: build-complete

#3219 php@7.3-debug-zts: Build for icu4c@75
  Formula/php@7.3-debug-zts.rb
Labels: build-complete

#3216 php@7.2-debug: Build for icu4c@75
  Formula/php@7.2-debug.rb
Labels: build-complete

#3218 php@7.2: Build for icu4c@75
  Formula/php@7.2.rb
Labels: build-complete

#3214 php@7.1: Build for icu4c@75
  Formula/php@7.2.rb
Labels: build-complete

#3209 php@7.0-zts: Build for icu4c@75
  Formula/php@7.0-zts.rb
Labels: build-complete

#3220 php@7.3-debug: Build for icu4c@75
  Formula/php@7.3-debug.rb
Labels: build-complete

#3217 php@7.2-zts: Build for icu4c@75
  Formula/php@7.2-zts.rb
Labels: build-complete

#3203 php@5.6-debug-zts: Build for icu4c@75
  Formula/php@5.6-debug-zts.rb
Labels: build-complete

#3221 php@7.3-zts: Build for icu4c@75
  Formula/php@7.3-zts.rb
Labels: build-complete

#3222 php@7.3: Build for icu4c@75
  Formula/php@7.3.rb
Labels: build-complete

#3247 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4

#3250 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3249 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3248 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3252 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4

#3254 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3253 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3251 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3257 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3255 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4

#3256 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3258 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3262 Update php@8.4-debug-zts
  Formula/php@8.4-debug-zts.rb
Labels: automated-pr, build-complete, php@8.4-debug-zts

#3261 Update php@8.4-zts
  Formula/php@8.4-zts.rb
Labels: automated-pr, build-complete, php@8.4-zts

#3260 Update php@8.4-debug
  Formula/php@8.4-debug.rb
Labels: automated-pr, build-complete, php@8.4-debug

#3259 Update php@8.4
  Formula/php@8.4.rb
Labels: automated-pr, build-complete, php@8.4
